services:
  - type: web
    name: emporio-pos-api
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: APP_ORIGIN
        sync: false
      - key: REQUIRE_HTTPS
        value: "true"
      - key: SPRING_PROFILES_ACTIVE
        value: "demo"
    healthCheckPath: /actuator/health
